config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'extractor#new'
  resources :extractor, only: %i[new create show] do
    collection do
      post :new_linguist
      post :create_linguist
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/linguist.rb
# frozen_string_literal: true

class Linguist < ApplicationRecord
  validates :first_name, :last_name, :country, :native_language, :target_language, :source, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/extractor_controller.rb
# frozen_string_literal: true

class ExtractorController < ApplicationController
  def new
    @form = NewLinkForm.new
  end

  def create
    @form = NewLinkForm.new(form_params)
    @form.validate!

    extracted_hash = Parsers::TranslatorParser.call(@form.link)
    @linguist = Linguist.new(extracted_hash)
  rescue ActiveModel::ValidationError
    render 'new', form: @form
  end

  def create_linguist
    @linguist = Linguist.new(linguist_params)
    @linguist.save!

    redirect_to extractor_path(@linguist.id)
  rescue ActiveRecord::RecordInvalid
    render 'create', linguist: @linguist
  end

  def show
    @linguist = Linguist.find(params[:id])
  end

  private

  def form_params
    params.require(:new_link_form).permit(:link)
  end

  def linguist_params
    params.require(:linguist).permit(:first_name, :last_name, :country, :language, :native_language, :target_language,
                                     :source)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/extractor/create.html.erb
<div class="centered">
  <div class="link-extractor">
    <h1 class="link-extractor__header">Take a look on extracted data</h1>
     <%= form_with model: @linguist, url: create_linguist_extractor_index_path, class: 'link-extractor__form' do |form| %>

      <% if @linguist.errors.any? %>
        <% @linguist.errors.full_messages.each do |message|%>
          <p class="link-extrator__error"><%= message %> </p>
        <% end %>
      <% end %>

      <div class="link-extractor__group">
        <%= form.label :first_name, 'First name', class: 'link-extractor__label' %>
        <%= form.text_field :first_name, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <%= form.label :last_name, 'Last name', class: 'link-extractor__label' %>
        <%= form.text_field :last_name, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <%= form.label :country, 'Country', class: 'link-extractor__label' %>
        <%= form.text_field :country, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <%= form.label :native_language, 'Native language', class: 'link-extractor__label' %>
        <%= form.text_field :native_language, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <%= form.label :target_language, 'Target language', class: 'link-extractor__label' %>
        <%= form.text_field :target_language, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <%= form.label :source, 'Source', class: 'link-extractor__label' %>
        <%= form.text_field :source, readonly: true, class: 'link-extractor__input', size: 40 %>
      </div>

      <div class="link-extractor__group">
        <div class="link-extractor__wrapper">
          <button class="link-extractor__button">Save</button>
          <%= link_to 'Back', root_path, class: 'link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/extractor/index.html.erb
<div class="centered">
  <div class="link-extractor">
    <h1 class="link-extractor__header">Extractor</h1>
    <%= form_with model: @form, url: extractor_index_path, class: 'link-extractor__form' do |form| %>

      <% if @form.errors.any? %>
        <% @form.errors.full_messages.each do |message|%>
          <p class="link-extrator__error"><%= message %> </p>
        <%end%>
      <%end%>

      <%= form.label :link, 'Link to a Proz profile', class: 'link-extractor__label' %>
      <div class="link-extractor__wrapper">
        <%= form.text_field :link, class: 'link-extractor__input', size: 40, placeholder: 'https://www.proz.com/profile/52171' %>
        <%= form.submit 'Extract', class: 'link-extractor__button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/extractor/new.html.erb
<div class="centered">
  <div class="link-extractor">
    <h1 class="link-extractor__header">Extractor</h1>
    <%= form_with model: @form, url: extractor_index_path, class: 'link-extractor__form' do |form| %>

      <% if @form.errors.any? %>
        <% @form.errors.full_messages.each do |message|%>
          <p class="link-extrator__error"><%= message %> </p>
        <% end %>
      <% end %>

      <%= form.label :link, 'Link to a Proz profile', class: 'link-extractor__label' %>
      <div class="link-extractor__wrapper">
        <%= form.text_field :link, class: 'link-extractor__input', size: 40, placeholder: 'https://www.proz.com/profile/52171' %>
        <%= form.submit 'Extract', class: 'link-extractor__button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/extractor/show.html.erb
<div class="centered">
  <div class="link-extractor">
    <h1 class="link-extractor__header"><%= @linguist.first_name %> <%= @linguist.last_name %></h1>
    <p><strong>Country</strong>: <%= @linguist.country %></p>
    <p><strong>Native language</strong>: <%= @linguist.native_language %></p>
    <p><strong>Target language</strong>: <%= @linguist.target_language %></p>
    <p><strong>Source</strong>: <%= @linguist.source %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravodParser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>